#!/usr/bin/env bash

tmux_running=$(pgrep tmux)

if [[ -z $tmux_running ]] || !(tmux has-session -t "timesipooped" 2>/dev/null); then
    tmux new-session -d -s timesipooped -n Vim 
fi

tmux send-keys -t timesipooped:0 'vim .' C-m

tmux new-window -t timesipooped:1 -n Server
tmux send-keys -t timesipooped:1 'cd cmd && air -c ../.air.toml' C-m

tmux split-window -t timesipooped:1 -h
tmux send-keys -t timesipooped:1 'npx live-server web --host=localhost --port=8080' C-m

tmux attach-session -t timesipooped
